### ISSUE TITLE
Cache TTL option

### ISSUE THREAD

**Issue by yani** [compwright/php-session#16]
Currently, there is no TTL for sessions stored in the cache. 

My custom Redis cache is filling up because sessions are not removed after a set amount of time.

**Comment by compwright** [comment]
These are controlled by the gcMaxLifetime config option. See https://github.com/compwright/php-session/blob/6b5968893357d8742090a1f9d812b3bb20807039/src/Config.php#L94

**Comment by yani** [comment]
It doesn't seem to be used.

**Comment by compwright** [comment]
It's used, check your config maybe? Note that RedisHandler extends ScrapbookHandler.

https://github.com/compwright/php-session/blob/6b5968893357d8742090a1f9d812b3bb20807039/src/Handlers/ScrapbookHandler.php#L99

**Comment by yani** [comment]
Oh I see. I'm using Symfony's RedisAdapter as my PSR6 and PSR16 Cache. It has a default lifetime of infinite. I changed it and the Session TTL also changed.

Wouldn't it be better to set the TTL when creating the Session in the cache?

PSR-16 CacheInterface:
```php
public function set($key, $value, $ttl = null);
```
