### ISSUE TITLE
Implement \ArrayObject and setter/getter method

### ISSUE THREAD

**Issue by yani** [compwright/php-session#4]
Example documentation in README demonstrates an array object:
```php
$session = $manager->getCurrentSession();
$session["foo"] = "bar";
unset($session["bar"]);
```

This is obsolete as it uses magic methods for dynamic properties and does not extend the \ArrayObject class:
```php
class Session implements \Countable {
    // ...
    public function __get(string $name)
    public function __set(string $name, $value): void
    // ...
}
```

What direction would you like to take?

My opinion is to go for all these:
- extend \ArrayObject (and throw an exception for non-existing variables like a normal array)
- add a `get($variable, $default = null);` and `set($variable, $value);` method as alternate syntax
- keep dynamic properties using magic methods `__get()` and `__set()` (current) but change `__get()` to throw an exception instead of returning null as it goes against normal dynamic property usage

The reason I suggest partially moving away from dynamic properties is because it behaves totally different from $_SESSION which is what many people are used to, and because [they are becoming deprecated in 8.2](https://php.watch/versions/8.2/dynamic-properties-deprecated). However, [the magic `__get()` and `__set()` methods will not be deprecated](https://php.watch/versions/8.2/dynamic-properties-deprecated#__get-__set), but I personally think people will start to move away from using dynamic properties in general. Which would make this library use/force an old syntax in a way. 

Reason I would still include dynamic properties is for backwards compatibility and for people who really like using it like this.

Let me know. I don't mind working on it and have the time. (I have my own session library which extends ArrayObject but isn't native like this one, so it wouldn't be too much work for me)

**Comment by compwright** [comment]
Dynamic properties are not deprecated in 8.2 when __get()/__set() are used. https://php.watch/versions/8.2/dynamic-properties-deprecated#__get-__set

**Comment by compwright** [comment]
> extend \ArrayObject (and throw an exception for non-existing variables like a normal array)

Instead, let's implement the [ArrayAccess](https://www.php.net/arrayaccess) interface in the class. It will get you the array-like behavior. That being missing is a bug.

> add a get($variable, $default = null); and set($variable, $value); method as alternate syntax

I don't personally see the need for this 🤷🏻 

> keep dynamic properties using magic methods __get() and __set() (current) but change __get() to throw an exception instead of returning null as it goes against normal dynamic property usage

Good idea, and needed (currently a bug) 👍🏻 

> I don't mind working on it and have the time.

Thank you! I'd love to have a PR from you to resolve these issues. Great feedback.

**Comment by yani** [comment]
> Instead, let's implement the [ArrayAccess](https://www.php.net/arrayaccess) interface in the class. It will get you the array-like behavior. That being missing is a bug.

My bad. Didn't double check :) ArrayAccess it is.

> > add a get($variable, $default = null); and set($variable, $value); method as alternate syntax
> 
> I don't personally see the need for this 🤷🏻
>
> > keep dynamic properties using magic methods __get() and __set() (current) but change __get() to throw an exception instead of returning null as it goes against normal dynamic property usage
> 
> Good idea, and needed (currently a bug) 👍🏻

Take those two points together and the `get($variable, $default = null); ` method would be the only way to retrieve a value with a default fallback value. Many people tend to use such functionality. This way is a non-magic way of doing it. Hence why it might be worth adding. 

> > I don't mind working on it and have the time.
> 
> Thank you! I'd love to have a PR from you to resolve these issues. Great feedback.

Will start working on it :)

**Comment by compwright** [comment]
> Take those two points together and the get($variable, $default = null);  method would be the only way to retrieve a value with a default fallback value.

What about...

```php
$foo = $session->bar ?? 'default';
```
